version: "2"
linters:
  enable:
    - bodyclose
    - goconst
    - gosec
    - misspell
    - prealloc
    - revive
  settings:
    gosec:
      excludes:
        - G304
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
          - goconst
          - staticcheck
        path: _test\.go
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
